service: html

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 #seconds
    memorySize: 128 #mb
